### ISSUE TITLE
unable to install under debian jessie

### ISSUE THREAD

**Issue by Ozzyboshi** [douglasvini/gimp-fanim#1]
I copied your 2 pyhon files under ~/.gimp-2.8/plug-ins but nothing happens.
Under gimp I go under help->plugin navigator and your plugin is not there, any suggestion?

**Comment by fergoy** [comment]
Ozzyboshi, I had the same problem, it went out that the files .py must have [execution permission assigned](https://roshanbook.wordpress.com/2012/01/06/make-sh-file-executable-in-linux/) maybe your problem is something like that.

**Comment by douglasvinis** [comment]
Yes, GIMP plugins under unix platforms needs execution permission. git don't transmit permissions, so when you download the source here is just a text file.
